# Generated by Django 3.0.7 on 2020-09-27 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20200927_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='orders',
        ),
        migrations.AddField(
            model_name='order',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', related_query_name='orders', to='bill.Bill'),
        ),
    ]
