# Generated by Django 3.0.7 on 2020-09-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='guestNULL', max_length=100),
        ),
    ]
